### ISSUE TITLE
The menu is not visible on tablets or cell phones

### ISSUE THREAD

**Issue by DannyFeliz** [developersdo/opensource#79]
### Desktop - Good
![2017-10-28 01_18_30-popular repositories dominican open source](https://user-images.githubusercontent.com/5460365/32131515-05b4742c-bb7e-11e7-9350-3a8246f356fa.png)

<hr>

### Tablet - Bad
![developersdo github io-opensource--p -repositories-popular ipad](https://user-images.githubusercontent.com/5460365/32131531-69d38b14-bb7e-11e7-8e4b-be3ce264c1f6.png)

<hr>

### Cell Phone - Bad
![developersdo github io-opensource-repositories-popular iphone 6 plus](https://user-images.githubusercontent.com/5460365/32131534-7c1ac9b8-bb7e-11e7-987d-0eb7abead94e.png)

### Tasks:

 - [ ] On medium and small device display a sandwich style menu. Please take a look at: http://materializecss.com/mobile.html

**Comment by Eduardoveras** [comment]
@rmariuzzo im working on this

**Comment by rmariuzzo** [comment]
Great!

On October 28, 2017, at 23:54, Eduardo Veras <notifications@github.com> wrote:

@rmariuzzo im working on this

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/developersdo/opensource","title":"developersdo/opensource","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/developersdo/opensource">https://github.com/developersdo/opensource</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Eduardoveras in #79: @rmariuzzo im working on this"}],"action":{"name":"View Issue","url":"<a href="https://github.com/developersdo/opensource/issues/79#issuecomment-340235786">https://github.com/developersdo/opensource/issues/79#issuecomment-340235786</a>"}}}

**Comment by Eduardoveras** [comment]
@rmariuzzo revisa que tu auto-reply no tenga informacion que no deba, veo un api-key de github ahi 😄

**Comment by rmariuzzo** [comment]
Fue un reply desee mi e-mail, parece ser algo interno de Github...

**Comment by rmariuzzo** [comment]
Gracias por decirme. Le voy a escribir a Github.
